---
title: "Midterm exam - Titanic analysis"
author: "Sydney Vie"
date: "2022-10-19"
output: html_document
---

# Load data and packages
```{r set up}

library(tidyverse) 
# for loading data, data management, and ggplot2

titanic <- read_csv("https://raw.githubusercontent.com/kijohnson/Data/main/titanic.csv")
# import Titanic dataset from GitHub

```

# Determine median age by passenger class
The median age differs by passenger class. The median age in passenger class 1 is 38.5 years. The median age in passenger class 2 is 29.0 years. The median age in passenger class 3 is 24.0 years.
```{r}

titanic$Pclass <- as.factor(titanic$Pclass)
# convert passenger class from a numeric to a factor variable 

medianAgeByClass <- titanic %>% 
  group_by(Pclass) %>% 
  summarise(medianAge = median(Age))
medianAgeByClass
# determine the median age grouped by passenger class

```

# Use a boxplot to visualize age according to passenger class
```{r}

ageClass <- ggplot(data = titanic, aes(x = Pclass, y = Age, fill = Pclass)) +
  geom_boxplot() +
  labs(title = "Median age by passenger class", 
       x = "Passenger class", y = "Age (years)", 
       fill = "Passenger class") +
  theme_minimal()
ageClass
# create a boxplot to visualize the medians, spread, and outliers of age by passenger class

```

# Determine percent of males and females by class
```{r}

titanic$Sex <- if_else(titanic$Sex == "male", 1, 0)
titanic$Sex <- factor(titanic$Sex,
                      levels = c(0,1),
                      labels = c("Female", "Male"))
# convert sex from a character to a factor variable

sexByClassCount <- table(titanic$Pclass, titanic$Sex)
sexByClassCount
# get a table of counts of males and females in each class

sexByClassPercent <- (prop.table(sexByClassCount, 1))*100  
sexByClassPercent
# get a table with the percent of males and percent of females in each class

sexbyClassTable <- cbind(sexByClassCount, sexByClassPercent)
sexbyClassTable
# merge the two tables to get a full table with counts and percentages

```

